name: example
description: siri_wave demo
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  siri_wave:
    path: ../

dev_dependencies:
  halildurmus_lints: ^2.0.0

flutter:
  uses-material-design: true
